# Validate selected AICC-managed agent-home directives without mutating runtime state.

[CmdletBinding()]
param(
    [Alias('Hub')][string]$AiccRoot = '',
    [string]$CatalogPath = '',
    [string[]]$TargetGroups = @(),
    [switch]$AllTargets,
    [switch]$AsJson,
    [switch]$SummaryOnly,
    [int]$MaxBytes = 16384,
    [int]$MaxLines = 200
)

$ErrorActionPreference = 'Stop'
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

if (-not $AiccRoot) { $AiccRoot = Join-Path $PSScriptRoot '../../..' }
$AiccRoot = (Resolve-Path -LiteralPath $AiccRoot).Path
$modulePath = Join-Path $AiccRoot 'tools/platform/core/AgentHomeDeployment.psm1'
if (-not (Test-Path -LiteralPath $modulePath -PathType Leaf)) { throw "Missing deployment module: $modulePath" }
Import-Module $modulePath -Force
if (-not $CatalogPath) { $CatalogPath = Join-Path $AiccRoot 'guidance/config/agent-catalog.toml' }

$checks = @()
function Add-Check {
    param([string]$Name, [bool]$Ok, [string]$Detail = '')
    $script:checks += [pscustomobject]@{ name=$Name; ok=$Ok; detail=$Detail }
}

$policy = Get-AgentHomeDeploymentPolicy -AiccRoot $AiccRoot -CatalogPath $CatalogPath
$selectedTargets = @(Select-AgentHomeDeploymentTargets -Policy $policy -TargetGroups $TargetGroups -AllTargets:$AllTargets)
$selectedIds = @($selectedTargets.id)
$selectedHomeFiles = @()
$optionalGeneratedFiles = @()
$mojibakePattern = '�|\?뱷|\?먯|\?쒓|\?섏|\?뚯'
$legacyPathPattern = 'C:/dev|C:\\dev'

Add-Check 'Default deployment groups are Codex and Claude only' (
    @($policy.default_groups).Count -eq 2 -and
    'codex' -in $policy.default_groups -and
    'claude' -in $policy.default_groups
) ($policy.default_groups -join ', ')
Add-Check 'Catalog has no optional deployment mode' ($policy.optional_mode -eq 'none') $policy.optional_mode
$gitignorePath = Join-Path $AiccRoot '.gitignore'
$gitignoreRaw = if (Test-Path -LiteralPath $gitignorePath -PathType Leaf) { Get-Content -LiteralPath $gitignorePath -Raw -Encoding UTF8 } else { '' }
Add-Check 'AICC ignores project-local Claude memory' ($gitignoreRaw -match '(?m)^CLAUDE\.local\.md\r?$')

foreach ($target in $selectedTargets) {
    Add-Check "$($target.id) rule/generated counts match" ($target.rules.Count -eq $target.generated.Count) "$($target.rules.Count)/$($target.generated.Count)"
    for ($index = 0; $index -lt [Math]::Min($target.rules.Count, $target.generated.Count); $index++) {
        $homePath = [string]$target.rules[$index]
        $generatedPath = [string]$target.generated[$index]
        $selectedHomeFiles += $homePath
        $homeExists = Test-Path -LiteralPath $homePath -PathType Leaf
        $generatedExists = Test-Path -LiteralPath $generatedPath -PathType Leaf
        Add-Check "$homePath exists" $homeExists
        Add-Check "$generatedPath exists" $generatedExists
        if (-not $homeExists -or -not $generatedExists) { continue }

        $item = Get-Item -LiteralPath $homePath
        $lines = @(Get-Content -LiteralPath $homePath -Encoding UTF8)
        $raw = $lines -join "`n"
        $homeHash = (Get-FileHash -LiteralPath $homePath -Algorithm SHA256).Hash
        $generatedHash = (Get-FileHash -LiteralPath $generatedPath -Algorithm SHA256).Hash
        Add-Check "$homePath matches generated source" ($homeHash -eq $generatedHash) "$homeHash / $generatedHash"
        Add-Check "$homePath byte budget" ($item.Length -le $MaxBytes) "$($item.Length) <= $MaxBytes"
        Add-Check "$homePath line budget" ($lines.Count -le $MaxLines) "$($lines.Count) <= $MaxLines"
        Add-Check "$homePath generated header" ($raw -match '(?m)^<!-- Generated by AICC; edit guidance/directives/fragments, not this file\. -->\r?$')
        Add-Check "$homePath no template variables" ($raw -notmatch '\$TargetAgentsPath|\$AgentName|\$CanonicalFile')
        Add-Check "$homePath no mojibake" ($raw -notmatch $mojibakePattern)
        Add-Check "$homePath no legacy path" ($raw -notmatch $legacyPathPattern)
    }
}

foreach ($target in @($policy.targets | Where-Object { $_.id -notin $selectedIds })) {
    foreach ($path in @($target.rules + $target.generated)) {
        if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { continue }
        $raw = Get-Content -LiteralPath $path -Raw -Encoding UTF8
        if ($raw -match '(?m)^<!-- Generated by AICC; edit guidance/directives/fragments, not this file\. -->\r?$') { $optionalGeneratedFiles += $path }
    }
}
Add-Check 'No AICC-generated directives remain in optional homes or generated output' ($optionalGeneratedFiles.Count -eq 0) ($optionalGeneratedFiles -join ', ')

$codexPath = Join-Path $policy.user_home '.codex/AGENTS.md'
if ('codex' -in $selectedIds -and (Test-Path -LiteralPath $codexPath -PathType Leaf)) {
    $raw = Get-Content -LiteralPath $codexPath -Raw -Encoding UTF8
    Add-Check 'Codex rules forbid guessed mutable values' ($raw -match '추측하거나 새로 고정하지 않는다')
    Add-Check 'Codex rules forbid silent target or provider fallback' ($raw -match '조용한 대상·계정·provider·데이터 범위 전환')
    Add-Check 'Codex rules keep native-first skill boundary' ($raw -match '네이티브 기능으로 충분한 절차는 별도 스킬로 만들지 않는다')
    Add-Check 'Codex rules use private coordination and safely gate browser state' (
        $raw -match 'Codex Desktop 내장 Browser를 백그라운드 기본값' -and
        $raw -match '~/.ai-control-center/guidance/coordination.toml' -and
        $raw -match '추측하지 않는다' -and
        $raw -match 'task-owned target' -and
        $raw -match '기존 사용자 브라우저는 명시 요청 또는 신뢰 가능한 독점 유휴 신호' -and
        $raw -match '높음\(high\)' -and
        $raw -match '매우 높음\(xhigh\)' -and
        $raw -match '명시 동의 전에는 Pro를 선택·제출하지 않는다'
    )
}

$claudeBridge = Join-Path $policy.user_home '.claude/CLAUDE.md'
if ('claude' -in $selectedIds -and (Test-Path -LiteralPath $claudeBridge -PathType Leaf)) {
    $raw = Get-Content -LiteralPath $claudeBridge -Raw -Encoding UTF8
    Add-Check 'Claude entrypoint imports sibling AGENTS.md' ($raw -match '(?m)^@AGENTS\.md\r?$')
    Add-Check 'Claude entrypoint contains Claude-only rules' ($raw -match '(?m)^## Claude Code\r?$')
    Add-Check 'Claude entrypoint keeps native-first extension boundary' ($raw -match 'MCP·Skill·Hook·Plugin·Subagent를 추가하지 않는다')
    Add-Check 'Claude entrypoint keeps browser identity boundary' ($raw -match '기존 로그인 세션이 필요한 경우에만 Claude in Chrome')
    Add-Check 'Claude entrypoint forbids silent browser fallback' ($raw -match '다른 계정·브라우저·포트·대상으로 조용히 전환하지 않는다')
}

$claudeAgents = Join-Path $policy.user_home '.claude/AGENTS.md'
if ('claude' -in $selectedIds -and (Test-Path -LiteralPath $claudeAgents -PathType Leaf)) {
    $raw = Get-Content -LiteralPath $claudeAgents -Raw -Encoding UTF8
    Add-Check 'Claude AGENTS.md contains shared rules' ($raw -match '(?m)^## 공통 로컬 경계\r?$')
    Add-Check 'Claude AGENTS.md excludes Claude-only rules' ($raw -notmatch '(?m)^## Claude Code\r?$')
}

$failed = @($checks | Where-Object { -not $_.ok })
$report = [ordered]@{
    ok = ($failed.Count -eq 0)
    default_target_groups = @($policy.default_groups)
    selected_target_groups = @($selectedIds)
    checked_home_file_count = $selectedHomeFiles.Count
    optional_generated_count = $optionalGeneratedFiles.Count
    check_count = $checks.Count
    failed_count = $failed.Count
    checks = @($checks)
}
if ($SummaryOnly) {
    $report = [ordered]@{
        ok = ($failed.Count -eq 0)
        default_target_groups = @($policy.default_groups)
        selected_target_groups = @($selectedIds)
        checked_home_file_count = $selectedHomeFiles.Count
        optional_generated_count = $optionalGeneratedFiles.Count
        check_count = $checks.Count
        failed_count = $failed.Count
        failed_checks = @($failed | Select-Object -First 20)
    }
}

if ($AsJson) { $report | ConvertTo-Json -Compress -Depth 7 } else { $report | ConvertTo-Json -Depth 7 }
if (-not $report.ok) { exit 1 }
