# Generate compact agent-home entrypoints from AICC directive fragments.

[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [Alias('Hub')][string]$AiccRoot = '',
    [string]$CatalogPath = '',
    [string[]]$TargetGroups = @(),
    [switch]$AllTargets,
    [string]$GeneratedTimestamp = '',
    [switch]$Plan,
    [switch]$PruneOptionalTargets,
    [switch]$AsJson
)

$ErrorActionPreference = 'Stop'
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

if (-not $AiccRoot) {
    $candidates = @($env:AICC_ROOT, (Join-Path $PSScriptRoot '../../..')) | Where-Object { $_ }
    $AiccRoot = @($candidates | Where-Object { Test-Path -LiteralPath (Join-Path $_ 'guidance/directives/fragments/common.md') -PathType Leaf } | Select-Object -First 1)
}
if (-not $AiccRoot) { throw 'Canonical AICC root was not found.' }
$AiccRoot = (Resolve-Path -LiteralPath $AiccRoot).Path
$generatedRoot = Join-Path $AiccRoot 'guidance/directives/generated'
$fragmentRoot = Join-Path $AiccRoot 'guidance/directives/fragments'
$modulePath = Join-Path $AiccRoot 'tools/platform/core/AgentHomeDeployment.psm1'
if (-not (Test-Path -LiteralPath $modulePath -PathType Leaf)) { throw "Missing deployment module: $modulePath" }
Import-Module $modulePath -Force
if (-not $CatalogPath) { $CatalogPath = Join-Path $AiccRoot 'guidance/config/agent-catalog.toml' }
$timestamp = if ($GeneratedTimestamp) { $GeneratedTimestamp } else { Get-Date -Format 'yyyy-MM-dd HH:mm:ss K' }

function Write-Utf8NoBom {
    param([Parameter(Mandatory)][string]$Path, [Parameter(Mandatory)][string]$Content)
    $parent = Split-Path -Parent $Path
    if ($parent -and -not (Test-Path -LiteralPath $parent)) { New-Item -ItemType Directory -Force -Path $parent | Out-Null }
    [System.IO.File]::WriteAllText($Path, ($Content.TrimEnd() + [Environment]::NewLine), [System.Text.UTF8Encoding]::new($false))
}

function Read-Fragment {
    param([Parameter(Mandatory)][string]$RelativePath)
    $path = Join-Path $fragmentRoot $RelativePath
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { throw "Missing directive fragment: $path" }
    return (Get-Content -LiteralPath $path -Raw -Encoding UTF8).Trim()
}

function New-Header {
    param([string]$AgentName, [string]$CanonicalFile)
    return '<!-- Generated by AICC; edit guidance/directives/fragments, not this file. -->' + [Environment]::NewLine
}

function New-AgentPolicy {
    param([string]$AgentName, [string]$CanonicalFile, [string]$AgentFragment)
    $break = [Environment]::NewLine
    return (New-Header $AgentName $CanonicalFile) + (Read-Fragment 'common.md') + $break + $break + (Read-Fragment $AgentFragment)
}

function New-CommonPolicy {
    param([string]$AgentName, [string]$CanonicalFile)
    return (New-Header $AgentName $CanonicalFile) + (Read-Fragment 'common.md')
}

function New-ClaudePolicy {
    $break = [Environment]::NewLine
    return (New-Header 'Claude' 'CLAUDE.md') + '@AGENTS.md' + $break + $break + (Read-Fragment 'agents/claude.md')
}

function Test-AiccGeneratedDirective {
    param([string]$Path)
    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { return $false }
    try { return (Get-Content -LiteralPath $Path -Raw -Encoding UTF8) -match '(?m)^(?:<!-- Generated by AICC; edit guidance/directives/fragments, not this file\. -->|<!-- Generated by Agent Hub; edit directives/fragments, not this file\. -->)\r?$' } catch { return $false }
}

$policy = Get-AgentHomeDeploymentPolicy -AiccRoot $AiccRoot -CatalogPath $CatalogPath
$selectedGroups = @(Select-AgentHomeDeploymentTargets -Policy $policy -TargetGroups $TargetGroups -AllTargets:$AllTargets)
$selectedIds = @($selectedGroups.id)

$policies = @{
    codex = New-AgentPolicy 'Codex' 'AGENTS.md' 'agents/codex.md'
    claude = New-CommonPolicy 'Claude' 'AGENTS.md'
}

$userHome = $policy.user_home
$targets = @(
    [pscustomobject]@{ Group='codex'; Agent='Codex'; Generated=(Join-Path $generatedRoot 'codex/AGENTS.md'); Home=(Join-Path $userHome '.codex/AGENTS.md'); Content=$policies.codex },
    [pscustomobject]@{ Group='claude'; Agent='Claude'; Generated=(Join-Path $generatedRoot 'claude/AGENTS.md'); Home=(Join-Path $userHome '.claude/AGENTS.md'); Content=$policies.claude },
    [pscustomobject]@{ Group='claude'; Agent='Claude'; Generated=(Join-Path $generatedRoot 'claude/CLAUDE.md'); Home=(Join-Path $userHome '.claude/CLAUDE.md'); Content=(New-ClaudePolicy) }
)

$actions = @()
$refused = @()
foreach ($target in @($targets | Where-Object { $_.Group -in $selectedIds })) {
    $actions += [ordered]@{ group=$target.Group; action='write'; home=$target.Home; generated=$target.Generated }
    if (-not $Plan -and $PSCmdlet.ShouldProcess($target.Home, "Deploy $($target.Agent) directive")) {
        Write-Utf8NoBom -Path $target.Generated -Content $target.Content
        Write-Utf8NoBom -Path $target.Home -Content $target.Content
    }
}

$report = [ordered]@{
    status = if ($Plan) { 'planned' } else { 'ok' }
    dry_run = [bool]$Plan
    timestamp = $timestamp
    catalog_path = $policy.catalog_path
    default_groups = $policy.default_groups
    selected_groups = $selectedIds
    prune_optional_targets = $false
    actions = $actions
    refused = $refused
}

if ($AsJson) { $report | ConvertTo-Json -Compress -Depth 6 } else { $report | ConvertTo-Json -Depth 6 }
